twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_5_layout.html.twig']
    globals:
        locales: '%app.locales%'
        CallAvatars: '@App\Service\CallAvatars'

when@test:
    twig:
        strict_variables: true
